- package.json
- src/ArchiveComponent.jsx
- src/SurveyComponent.jsx
- src/VirtualInstallation.jsx
Linting `.jsx` as well as `.js`.
This PR will be merged immediately.
> ci: linting of .jsx

- README.md
- package.json
- Change a homepage in `package.json`.
- Change URL in README.
> Edit documents related to changing owner

- README.md
- src/App.js
The URL will be changed to reflect the transfer of the repository.
This PR will be merged immediately.
> fix: update URLs

- src/App.js
Allows you to review apm-data issues related to plugins and scripts.
> feat: change issue filtering options

- package.json
- yarn.lock
Use the cross-enviroment supported command instead of the `cp` command.
> feat: multi-environmentalization of scripts

- src/App.js
Disables the send button when there is no data to send.
> feat: disable send button if necessary

- package.json
- yarn.lock
Remove fast-xml-parser dependency. This PR will be merged immediately.
> build: remove fast-xml-parser

- src/components/SurveyComponent.tsx
Fix the bugs where integrity was not generated and the download button was not displayed.
This PR will be merged soon.
> fix: integrity was not generated

- .github/workflows/gh-pages.yml
- README.md
- package.json
Automate apm-web deployments. Also simplifies manual deployments.
- Testing is done after the merge.
> feat: simplify deployment

- .eslintrc
- src/components/App.tsx
- tsconfig.json
Add a button to load json data for packages. This will facilitate editing of package data submitted to apm-data.
- https://github.com/team-apm/apm-data/issues/423 can be loaded by "パッケージを読み込む" button.
> feat: package data import function

- .prettierrc
- package.json
- public/index.html
- src/components/App.tsx
- src/components/ArchiveComponent.tsx
- src/components/SurveyComponent.tsx
- src/components/VirtualInstallation.tsx
- src/index.js
- yarn.lock
- Remove `prettier-plugin-md-nocjsp`.
- Bump prettier from 2.8.8 to 3.0.2.
- Apply formatting
> build(deps-dev): remove prettier-plugin-md-nocjsp and bump prettier from 2.8.8 to 3.0.2

- .github/workflows/gh-pages.yml
- next.config.js
- package.json
- Fix deploying by gh-pages.
- I don't know about Next.js in detail but I referred to this document.
- https://nextjs.org/docs/pages/building-your-application/deploying/static-exports
I deployed it to gh-pages.
> build: fix deploying by gh-pages

- next.config.js
- package.json
I forgot to specify a `basePath` in next.js that corresponds to the `homepage` of the create react app.
I will merge it immediately because of minor modifications.
> fix: update basePath

- .github/workflows/dependabot-auto-merge.yml
> ci(GitHub Actions): change to assign reviewer

- .github/workflows/gh-pages.yml
- .github/workflows/nodejs.yml
- package.json
- src/app/components/main.css
- yarn.lock
> build(deps-dev): bump dependencies

- tsconfig.json
> build(tsconfig.json): add additional path to include for TypeScript types to avoid an error

- .github/workflows/gh-pages.yml
- package.json
> fix(deploy): update artifact path for GitHub Pages deployment

- package.json
- yarn.lock
- update bootstrap-icons, next, survey-react, and devDependencies
I will merge this PR soon.
> build(deps): update bootstrap-icons, next, survey-react, and devDependencies

- package.json
- yarn.lock
> build(deps): update survey-react and @types/node, @types/react, lint-staged, npm-run-all2, and prettier-plugin-packagejson

- src/app/layout.tsx
- change HTML lang attribute from 'en' to 'ja' for localization in the root layout
> fix: update HTML lang attribute from 'en' to 'ja' for localization
